- name: Remove Airport db
  hosts: airportserver
  tasks:
    - name: Clear Airport db
      shell: echo > /home/{{ remote_user }}/Airport/__airport.db
    - name: Restart server
      shell: /home/{{ remote_user }}/Airport/runairport ansible
      async: 10
      poll: 0
